name: Git Commit Security Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Run Git Commit Security Analyzer
        uses: pixelotes/git-commit-analyzer@feat/gha-webhook-support
        with:
          model: 'qwen2.5-coder:1.5b'
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
  
      # Optionally, you can upload the report as an artifact 
      - name: Upload security report artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.json
